"""empty message

Revision ID: 545f01d74256
Revises: 0f112daec1e6
Create Date: 2016-12-28 11:56:42.680000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545f01d74256'
down_revision = '0f112daec1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default=u'', nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('journey',
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('journey_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('lastname', sa.String(length=50), server_default=u'', nullable=True),
    sa.Column('email', sa.Unicode(length=255), server_default=u'', nullable=False),
    sa.Column('username', sa.Unicode(length=255), server_default=u'', nullable=False),
    sa.Column('password', sa.Unicode(length=255), server_default='', nullable=False),
    sa.Column('user_creationDate', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('journey_version',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.journey_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'journey_id', 'version_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journey_version')
    op.drop_table('user')
    op.drop_table('journey')
    op.drop_table('supplier')
    # ### end Alembic commands ###
