"""empty message

Revision ID: 36b582af7d81
Revises: 
Create Date: 2017-01-31 13:15:20.272000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36b582af7d81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_journey_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('filename', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('status', sa.String(length=10), server_default=u'', nullable=False),
    sa.Column('description', sa.String(length=150), server_default=u'', nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journey_step',
    sa.Column('journey_step_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('description', sa.String(length=150), server_default=u'', nullable=False),
    sa.Column('short_name', sa.String(length=20), server_default=u'', nullable=False),
    sa.PrimaryKeyConstraint('journey_step_id')
    )
    op.create_table('permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('short_name', sa.Unicode(length=255), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('supplier',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('description', sa.String(length=150), server_default=u'', nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('journey',
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('description', sa.String(length=150), server_default=u'', nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('journey_id')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('lastname', sa.String(length=50), server_default=u'', nullable=True),
    sa.Column('email', sa.Unicode(length=255), server_default=u'', nullable=False),
    sa.Column('username', sa.Unicode(length=255), server_default=u'', nullable=False),
    sa.Column('password', sa.Unicode(length=255), server_default='', nullable=False),
    sa.Column('user_creationDate', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('journey_version',
    sa.Column('journey_version_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=True),
    sa.Column('validator', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('extensions', sa.String(length=150), server_default=u'', nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.journey_id'], ),
    sa.PrimaryKeyConstraint('journey_version_id')
    )
    op.create_table('user_session',
    sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('journey_version_role',
    sa.Column('journey_version_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_version_id'], ['journey_version.journey_version_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('journey_version_id', 'role_id')
    )
    op.create_table('journey_version_step',
    sa.Column('journey_version_id', sa.Integer(), nullable=False),
    sa.Column('journey_step_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_step_id'], ['journey_step.journey_step_id'], ),
    sa.ForeignKeyConstraint(['journey_version_id'], ['journey_version.journey_version_id'], ),
    sa.PrimaryKeyConstraint('journey_version_id', 'journey_step_id')
    )
    op.create_table('schedule',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('journey_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journey_version_id'], ['journey_version.journey_version_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.schedule_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('schedule')
    op.drop_table('journey_version_step')
    op.drop_table('journey_version_role')
    op.drop_table('user_session')
    op.drop_table('journey_version')
    op.drop_table('user')
    op.drop_table('role_permission')
    op.drop_table('journey')
    op.drop_table('supplier')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('journey_step')
    op.drop_table('file_journey_audit')
    # ### end Alembic commands ###
