"""empty message

Revision ID: 0f603b31ae20
Revises: 
Create Date: 2016-12-20 15:45:13.786000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f603b31ae20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_version',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.journey_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'journey_id', 'version_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journey_version')
    # ### end Alembic commands ###
