"""empty message

Revision ID: 365db1bf9822
Revises: 
Create Date: 2017-01-10 16:50:04.252000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '365db1bf9822'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_version',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journey.journey_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'journey_id', 'version_number')
    )
    op.drop_table('journey_step')
    op.drop_table('file')
    op.drop_table('file_journey_audit')
    op.add_column('journey', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'journey', 'supplier', ['supplier_id'], ['supplier_id'])
    op.drop_column('journey', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journey', sa.Column('description', sa.VARCHAR(length=150), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'journey', type_='foreignkey')
    op.drop_column('journey', 'supplier_id')
    op.create_table('file_journey_audit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=50), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=150), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text(u'now()'), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=50), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'file_journey_audit_pkey')
    )
    op.create_table('file',
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('file_id', name=u'file_pkey')
    )
    op.create_table('journey_step',
    sa.Column('step_id', sa.INTEGER(), nullable=False),
    sa.Column('journey_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=150), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=20), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], [u'journey.journey_id'], name=u'journey_step_journey_id_fkey'),
    sa.PrimaryKeyConstraint('step_id', name=u'journey_step_pkey')
    )
    op.drop_table('journey_version')
    # ### end Alembic commands ###
