"""empty message

Revision ID: ba7bd08fc2a7
Revises: 
Create Date: 2017-01-10 13:01:25.542000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7bd08fc2a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_journey_audit', sa.Column('step', sa.String(length=50), server_default=u'', nullable=False))
    op.drop_constraint(u'file_journey_audit_step_id_fkey', 'file_journey_audit', type_='foreignkey')
    op.drop_column('file_journey_audit', 'step_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_journey_audit', sa.Column('step_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'file_journey_audit_step_id_fkey', 'file_journey_audit', 'journey_step', ['step_id'], ['step_id'])
    op.drop_column('file_journey_audit', 'step')
    # ### end Alembic commands ###
