"""empty message

Revision ID: ecfca86b45b9
Revises: 
Create Date: 2017-01-10 22:53:19.361000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfca86b45b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default=u'', nullable=False),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('file_journey_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('filename', sa.String(length=50), server_default=u'', nullable=False),
    sa.Column('status', sa.String(length=10), server_default=u'', nullable=False),
    sa.Column('description', sa.String(length=150), server_default=u'', nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_journey_audit')
    op.drop_table('file')
    # ### end Alembic commands ###
